apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: superstreaming
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
