apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: superstreaming
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.superstreaming.svc.cluster.local:9090
        isDefault: true
        editable: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-provider
  namespace: superstreaming
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: SuperStreaming
        folder: SuperStreaming
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /etc/grafana/dashboards
