apiVersion: v1
kind: ConfigMap
metadata:
  name: mediamtx-read-config
  namespace: superstreaming
data:
  mediamtx.yml: |
    logLevel: info
    logDestinations:
      - stdout

    api: true
    apiAddress: :9997

    metrics: true
    metricsAddress: :9998

    rtsp: false

    webrtc: true
    webrtcAddress: :8889
    webrtcLocalUDPAddress: :8189
    webrtcLocalTCPAddress: :8189
    webrtcAdditionalHosts:
      - $WEBRTC_EXTERNAL_HOST

    authMethod: internal
    authInternalUsers:
      - user: any
        pass: ""
        permissions:
          - action: api
      - user: viewer
        pass: $VIEWER_SECRET
        permissions:
          - action: read
            path: ""

    paths:
      "~^(.+)$":
        source: rtsp://internal:$INTERNAL_SECRET@$ORIGIN_HOST:8554/$G1
        sourceOnDemand: true
