apiVersion: v1
kind: Service
metadata:
  name: mediamtx-origin-headless
  namespace: superstreaming
spec:
  clusterIP: None
  selector:
    app: mediamtx-origin
  ports:
    - name: rtsp
      port: 8554
      protocol: TCP
    - name: api
      port: 9997
      protocol: TCP
    - name: metrics
      port: 9998
      protocol: TCP
