apiVersion: v1
kind: Service
metadata:
  name: mediamtx-origin-publisher
  namespace: superstreaming
spec:
  selector:
    app: mediamtx-origin
  ports:
    - name: rtsp
      port: 8554
      targetPort: 8554
      nodePort: 30554
  type: NodePort
