apiVersion: v1
kind: Service
metadata:
  name: mediamtx-read
  namespace: superstreaming
spec:
  type: NodePort
  selector:
    app: mediamtx-read
  ports:
    - name: webrtc-http
      port: 8889
      targetPort: 8889
      nodePort: 30889
      protocol: TCP
    - name: webrtc-udp
      port: 8189
      targetPort: 8189
      nodePort: 30189
      protocol: UDP
    - name: webrtc-tcp
      port: 8189
      targetPort: 8189
      nodePort: 30189
      protocol: TCP
